### ISSUE TITLE
Configure MatNWB in order to read a file in format NWB2.0.2.

### ISSUE THREAD

**Issue by Alexandre-aksenov** [NeurodataWithoutBorders/matnwb#189]
Hello! I am trying to open the first file from the repository https://figshare.com/collections/Human_ECoG_speaking_consonant-vowel_syllables/4617263 (called EC9_B53.nwb, size: 2.5Gb) using MatNWB in order to process it later using Matlab. I could download the file successfully and open it in HDFView 3.1.0.

Afterwards, I downloaded:
the latest release (matnwb-0.2.3) from https://github.com/NeurodataWithoutBorders/matnwb/releases ,
and the latest release (nwb-schema-2.2.2) from https://github.com/NeurodataWithoutBorders/nwb-schema/releases.

I executed the following sequence of instructions on Matlab 9.7.0.1261785 (R2019b) Update 3.

>> generateCore();
-> (2 directories created) 
>>addpath('{path to MatNWB}/MatNWB/matnwb-0.2.3');

(in the folder with the NWB file) >>nwb=nwbRead('EC9_B53.nwb');
->
Unable to resolve the name types.core.DynamicTableRegion.

Error in io.parseDataset (line 76)
    parsed = eval([typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);

With the little documentation I have found, I can make the hypothesis that the outcome of my first attempt may result from the file format (the file claims to be of the NWB format, version 2.0.2) or from it being written using different software (such as pyNWB).

Thanks for Your attention.

**Comment by ln-vidrio** [comment]
Hi Alexandre,

This file looks to be made before cached schemas existed, thus you cannot read directly from the file without a generated schema.  Let me get back to you with the correct schema version you will need to read this file in MatNWB.

**Comment by ln-vidrio** [comment]
I apologize beforehand as this will be a little more involved than one would expect.  However, without a cached schema, a generateCore() call must be made with the valid schema version (in your case, this is 2.0.2).  Otherwise, reading is essentially not possible.

In any case, the pynwb commit NeurodataWithoutBorders/pynwb@ea88a12836 hosts a workable schema (it does not exist on nwb-schema so you will, unfortunately, have to poach from pynwb).  Instructions to read the file are below:

1. clone/download the pynwb repo (NeurodataWithoutBorders/pynwb@ea88a12836) at that commit hash (`git checkout ea88a12836` or you can download directly from the repo itself)
2. In the pynwb repo, copy everything in the directory `src/pynwb/data`.  These are your schema files that you will need.
3. If you haven't already, clone/download the MatNWB repository.  The most recent release should work fine.
4. Delete all files with the `.yaml` extension in `nwb-schema/core` in MatNWB.
5. Copy the contents of `/src/pynwb/data` from the PyNWB repository into `nwb-schema/core` in the MatNWB repository.
6. Run the `generateCore` script in MATLAB.
7. call `nwb = nwbRead('EC9_B53.nwb');`  This should work fine

From initial inspection, the data looks fine.  Let me know if you run into any data-related problems.

**Comment by Alexandre-aksenov** [comment]
Thank you for the instructions! This could indeed read the contents to a Matlab variable of type 'NwbFile'. Now I need to understand the structure of the file using: 
the output of HDFView, and the source codes of the new classes.

Best wishes in developing this library and making it useful !

**Comment by ln-vidrio** [comment]
Good to hear that it worked well!

The structure of each class should roughly match by group name in the HDFView output save a few name merges.  All generated types are in `+types/+core/*` in the MatNWB directory.  The NwbFile object is simply an extension of `types.core.NWBFile` which represents the root (or `/`) of the HDFView.  Apologies that the docs are not terribly helpful, as they are for a more recent NWB schema version.

You can peruse the tutorials as well if you wish to see example cases for utilizing the NwbFile class.
