### ISSUE TITLE
default args for DataPipe

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#195]
@IvanSmal and I have been able to successfully use `DataPipe` to compress data in NWB files, but we have found that the results can be very sensitive to the settings in `DataPipe`. There is little guidance for what would be reasonable parameters, and I would not expect many users to have a good intuition for what to use. I think it would be easier to use if we intelligently set some of these arguments. When MATLAB saves data using a an HDF5 backend using `save`, it has a way of automatically determining `compressionLevel` and `chunkSize`. It looks to me like MATLAB always defaults to GZIP level 3. It looks like the chunkSize is computed based on the shape of the matrix. I can't find where this is computed though.

Here is how I would propose we treat each argument of `DataPipe`:
* `maxSize`: Why is this an ordered arg and not a name, value arg? If `data` is supplied, and `maxSize` is not, `maxSize` should take the shape of data, except the `axis` dimension should be `Inf`, which would allow you to append in that dimension indefinitely.
* `dataType`: If `data` is supplied, we should infer `dataType` from it.
* `compressionLevel`: Use MATLAB default (3 I think)
* `chunkSize`: Use MATLAB default (if we can find the code for it)

**Comment by bendichter** [comment]
see https://github.com/h5py/h5py/blob/2273d17f1dce624215f80d9c65271c28a62a2e5f/h5py/_hl/filters.py#L330

**Comment by ln-vidrio** [comment]
@IvanSmal, @bendichter  I have added a new branch #197 that simplifies the DataPipe initialization.  Keyword arguments are no longer used, and there are two new static methods fromFile and fromData which will also instantiate a DataPipe.

- fromFile() takes two arguments filename and hdf5 path to a pre-existant DataPipe dataset.  The appending axis is assumed to be 1.

- fromData() takes one argument and an optional `axis` argument to indicate the appending axis index.  If omitted, the assumed axis is the first index of the maxSize.

- the regular DataPipe constructor now only takes two arguments: `maxSize` and `axis` which are both required.

Default compression is now level 3 instead of disabled.

Let me know what you think.
