### ISSUE TITLE
descriptions should not be allowed to be cell arrays

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#289]
The "description" field should not be able to be an array. A user can enter

```matlab
timeseries = types.core.TimeSeries( ...
    'data', [1,2,3], ...
    'description', {'aa' 'aa'}, ...
    'starting_time_rate', 100, ...
    'data_unit', 'na');
```

and no error is raised, but this results in an object with an incorrect description that cannot be opened by PyNWB

**Comment by ln-vidrio** [comment]
So we should assume that "text" types are scalar strings unless they specify dims? Assuming that all `text` types like `description` are scalar will break `colnames` in DynamicTable.

Otherwise, I can just hard-code all `description` properties to be scalar and assume other `text` types are not necessarily scalar.

**Comment by bendichter** [comment]
We should assume that "text" types are scalar strings unless they specify dims.

**Comment by ln-vidrio** [comment]
Yeah that seemed like the default behavior anyway which means I just need to move the workaround for character arrays elsewhere.

**Comment by ln-vidrio** [comment]
Does #290 work for you?
