### ISSUE TITLE
change tutorials to use `addRow`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#307]

**Comment by lawrence-mbf** [comment]
@bendichter I think this is mostly done. Which tutorials still don't use `addRow`?

**Comment by ehennestad** [comment]
- [ ] `behavior.mlx`
- [ ] `dynamic_tables.mlx`
- [ ] `ecephys.mlx`
- [ ] `icephys.mlx` Relevant?
- [ ] `images.mlx` No dynamic tables
- [ ] `intro.mlx`
- [ ] `ogen.mlx` - No dynamic tables
- [ ] `ophys.mlx` - PlaneSegmentation object created in one go
- [ ] `scratch.mlx` - No dynamic tables

**Comment by ehennestad** [comment]
It seems like this issue is no longer relevant. The Icephys tutorial has several dynamic tables, and the `addRow` method is not used, but I am also not sure if that is relevant. Closing this @bendichter, but if you think the icepys tutorial needs an example where the `addRow` method should be used, please reopen!
