### ISSUE TITLE
[Bug]: Unexpected attributes with nwbRead Dandiset 000115

### ISSUE THREAD

**Issue by hungtuchen** [NeurodataWithoutBorders/matnwb#470]
### What happened?

`Unexpected properties {camera_device 1}` when using `nwbRead` to read data file `https://dandiarchive.org/dandiset/000115/0.210914.1732/sub-despereaux/sub-despereaux_ses-despereaux-07_behavior+ecephys.nwb`.

### Steps to Reproduce

```matlab
addpath(genpath(pwd));
generateCore();
nwb = nwbRead('pathname_to_file')

And `util.getSchemaVersion('pathname_to_file')` returns '2.3.0'
```

### Error Message

```matlab
Error using assert
Unexpected properties {camera_device 1}.

Your schema version may be incompatible with the file.  Consider checking the schema version of the
file with `util.getSchemaVersion(filename)` and comparing with the YAML namespace version present in
nwb-schema/core/nwb.namespace.yaml

Error in types.util.checkUnset (line 13)
assert(isempty(dropped),...

Error in types.ndx_franklab_novela.NwbImageSeries (line 11)
            types.util.checkUnset(obj, unique(varargin(1:2:end)));

Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 59)
nwb = io.parseGroup(filename, h5info(filename), Blacklist); 
```
```


### Operating System

macOS

### Matlab Version

R2022b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by bendichter** [comment]
Hey @transedward thanks for opening the issue. This is going to be a bit tricky to reproduce because it's a 90 GB file. In Python I'd just stream it using fsspec, but the tools to do this in MATLAB are not as good. I'm downloading the file but it could take a while.

Looking at the traceback it looks like the issue is with the ndx_franklab_novela extension, not the core schema. Is it possible that you generated the schema for this extension and that it conflicts with the schema in the file? @lawrence-mbf , any thoughts on this?

**Comment by lawrence-mbf** [comment]
I agree that it's most likely coming from the extension schema and not the main one. I just finished downloading a representative file and it seems to come from the `CameraDevice` object which does come from the `ndx-franklab-novela` extension schema.

**Comment by lawrence-mbf** [comment]
I think see what the issue is. It has to do with the modifications to the `device` property in the core `ImageSeries`. The problematic type--NwbImageSeries--has modified the property to expand it to contain multiple Device objects. This causes a subtle breakage where the default value of `device` is not supposed to be `[]` as expected by `checkUnset`.

**Comment by yarikoptic** [comment]
Is the fix coming?

**Comment by lawrence-mbf** [comment]
It requires a larger change to class generation where `checkUnset` is used. But yes, working on it.

**Comment by lawrence-mbf** [comment]
@transedward @yarikoptic Let me know if #475 fixes this issue.

**Comment by lawrence-mbf** [comment]
Good to hear! I'll check on that error in the original file anyway in the meantime.
