### ISSUE TITLE
outputting links

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#48]
in the code

```
dev = types.core.Device( ...
    'source', ns_path);
file.general_devices.set('dev1', dev);

eg = types.core.ElectrodeGroup('source', ns_path, ...
    'description', 'a test ElectrodeGroup', ...
    'location', 'unknown', ...
    'device', types.untyped.SoftLink('/general/devices/dev1'));
file.general_extracellular_ephys.set('elec1', eg);
```

I don't like that you have to know the path of `dev1` in order to link it. I think that makes it hard for new users that might not know the hierarchical structure of nwb-schema. How would you feel about having `file.general_devices.set` optionally output the `SoftLink` object if an output is requested?

so the new syntax would be

```
dev = types.core.Device( ...
    'source', ns_path);
dev_link = file.general_devices.set('dev1', dev);

eg = types.core.ElectrodeGroup('source', ns_path, ...
    'description', 'a test ElectrodeGroup', ...
    'location', 'unknown', ...
    'device', dev_link);
file.general_extracellular_ephys.set('elec1', eg);
```

**Comment by ln-vidrio** [comment]
Since SoftLinks are expecting full paths it's a bit finicky if we just look at the `subsref` list.  How do you think we should approach it this way?

Another possible idea is to use dot notation similar to one of MATLAB's options for `edit`:
https://www.mathworks.com/help/matlab/ref/edit.html?searchHighlight=edit&s_tid=doc_srchtitle#btk4bs6-file
Basically, instead of:
`types.untyped.SoftLink('/general/devices/dev1')`
We have:
`types.untyped.SoftLink('general_devices.dev1')`
Implementing the above will require adding the functionality to `io.resolvePath` (trivial) as well as a converter for export functions (not as trivial).

**Comment by bendichter** [comment]
This has been fixed
