### ISSUE TITLE
round trip fails for TimeSeries data

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#56]
```matlab
file = nwbfile( ...
    'source', 'sdf', ...
    'session_description', 'a test NWB File', ...
    'identifier', 'sdf', ...
    'session_start_time', datestr(now, 'yyyy-mm-dd HH:MM:SS'), ...
    'file_create_date', datestr(now, 'yyyy-mm-dd HH:MM:SS'));


ts = types.core.TimeSeries('source', 'source',...
    'starting_time',0,...
    'starting_time_rate',3,...
    'data',[1,2,3],...
    'data_units','V?');
file.acquisition.set('test', ts);

nwb_path = 'test.nwb';
nwbExport(file, nwb_path)
nwb_read = nwbRead(nwb_path);
```

```
Undefined function 'keys' for input arguments of type 'types.untyped.DataStub'.

Error in io.parseGroup>elide (line 77)
    ekeys = keys(set);

Error in io.parseGroup (line 58)
        props(etp) = elide(etp, props);

Error in io.parseGroup (line 26)
    subg = io.parseGroup(filename, g_info);

Error in io.parseGroup (line 26)
    subg = io.parseGroup(filename, g_info);

Error in nwbRead (line 20)
nwb = io.parseGroup(filename, info);

Error in TDT2NWB (line 146)
nwb_read = nwbRead(nwb_path);
```

Interestingly this is *not* an issue for derived classes like `ElectricalSeries`. I may be entering something wrong here, but it would be better if errors occurred on write rather than on read.

**Comment by ln-vidrio** [comment]
So invalid property name/value pairs are actually dropped on construction so it wouldn't know about invalid property names on write.  I'm taking a look at this but the reason why this hasn't been implemented right now is because it's not clear whether or not a misspelled property is actually a subclass/superclass property.

**Comment by bendichter** [comment]
It would be nice if the read error pointed me to the value that's causing the problem (data_unit in this case).

Also, we could address this by building a read test into write (with the ability to turn it off for maximum performance).

**Comment by ln-vidrio** [comment]
b30ac10f6c6164d00f9f49ba917f5edc6c8eae21
So this will point out the property names on construction which will in turn cause errors whenever you read a file.
I'm unsure if I want to error it out like this.  For longer scripts I'd imagine that this is for the best but it might render nwb files unfixable since you can't read them.

**Comment by ln-vidrio** [comment]
fyi this actually breaks the ElectricalSeriesIO tests but in an expected way.  I'll work on fixing that.

**Comment by ln-vidrio** [comment]
3c69c3493dbc5c83d2d4b472b815e5e66cc75621
